services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_finances
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finances
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d finances"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_finances
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/finances?sslmode=disable
    volumes:
      - .:/app

volumes:
  pgdata: